services:
  mongo1:
    image: mongo:7.0
    container_name: mongo1
    # BẮT BUỘC: --port phải khớp với port bên ngoài
    command:
      ["mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "${MONGODB_PRIMARY_PORT:-27021}"]
    ports:
      # Sửa lại thành PORT:PORT (Ví dụ 27021:27021)
      - "${MONGODB_PRIMARY_PORT:-27021}:${MONGODB_PRIMARY_PORT:-27021}"
    volumes:
      - mongo1_data:/data/db
    networks:
      - mongo-cluster
    restart: unless-stopped

  mongo2:
    image: mongo:7.0
    container_name: mongo2
    command:
      ["mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "${MONGODB_SECONDARY1_PORT:-27022}"]
    ports:
      - "${MONGODB_SECONDARY1_PORT:-27022}:${MONGODB_SECONDARY1_PORT:-27022}"
    volumes:
      - mongo2_data:/data/db
    networks:
      - mongo-cluster
    restart: unless-stopped

  mongo3:
    image: mongo:7.0
    container_name: mongo3
    command:
      ["mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "${MONGODB_SECONDARY2_PORT:-27023}"]
    ports:
      - "${MONGODB_SECONDARY2_PORT:-27023}:${MONGODB_SECONDARY2_PORT:-27023}"
    volumes:
      - mongo3_data:/data/db
    networks:
      - mongo-cluster
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: my-redis-compose
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - mongo-cluster
    restart: unless-stopped

networks:
  mongo-cluster:
    driver: bridge

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
